### PR TITLE
[1.x] Sends data property when empty

### LINKED ISSUE #123: Missing 'data' property in 'pusher_internal:subscription_succeeded' event
### Reverb Version

1.0.0-beta4

### Laravel Version

11.1.1

### PHP Version

8.3.4

### Description

Hello!

This issue targets missing `data` property in `pusher_internal:subscription_succeeded` event, in response to connecting to private or public channel.

### Overview

Official Pusher server provides following payload for previously mentioned event:
```json
{
  "event": "pusher_internal:subscription_succeeded",
  "data": "{}",
  "channel": "my-channel"
}
```
This can be easily verfied with JavaScript example after creating sandbox app in Pusher.

Laravel Reverb does not send `data` property for such event:
```json
{
  "event": "pusher_internal:subscription_succeeded",
  "channel": "my-channel"
}
```
For JavaScript Pusher-compatible clients it's irrelevant as these can gracefully handle missing property. However, using Laravel Reverb as Pusher server for mobile application on iOS platform - written in Flutter and using forked official Pusher package (https://pub.dev/packages/pusher_channels_flutter) to allow server details customization - makes websocket unusable for apps that rely on that event, as Pusher Swift implementation does not properly parse payload and does not emit `subscription_succeeded`, which makes it impossible to react for such event.

### Solving problem

To make `data` property available in event payload we could simply remove `empty($data)` condition in `EventHandler::formatPayload` method and assign result of JSON encoding directly to that property, as following:
```php
return json_encode(
            array_filter([
                'event' => $prefix.$event,
                'data' => json_encode($data),
                'channel' => $channel,
            ])
        );
```
But this solution will result in payload containing `data: '[]'`. To be fully compatible with Pusher official server I suggest to modify mentioned condition and return string `'{}'` instead of null for empty data, and encoded JSON for other cases.

I've prepared PR for this solution.

Best regards!

### Steps To Reproduce

Very basic Laravel application with installed Reverb and JavaScript Echo connecting to websocket channel will provide described results.

### PR DESCRIPTION
**Pull request by jabools**
This PR fixes missing `data` property for `pusher_internal` events.

Fixes #123

### CODE REVIEW

**Comment by jabools** [comment]
Working on test fixes.

File: src/Protocols/Pusher/EventHandler.php [hunk 1]
```diff
@@ -145,12 +145,12 @@ public function sendInternally(Connection $connection, string $event, array $dat
     /**
      * Format the payload for the given event.
      */
-    public function formatPayload(string $event, array $data = [], ?string $channel = null, string $prefix = 'pusher:'): string|false
+    public function formatPayload(string $event, array $data = [], ?string $channel = null): string|false
```
Comment (jabools) [inline src/Protocols/Pusher/EventHandler.php:148]: The `$prefix` argument was used only for changing internal events prefix (and in tests). As it seems to have only one purpose - provide `pusher:` prefix, I decided to remove it and provide dedicated implementation for internal events payload.

**Comment by joedixon** [comment]
@jabools I'm pretty happy with the implmentation after a couple of tweaks, but interested if you can point me to the part of the Pusher docs which says this is a requirement. I can only see it in the Presence channel docs which we already handle and I'm reluctant to send more data across the wire than necessary.

**Comment by jabools** [comment]
Unfortunately, I am not able to find anything that would make that property a requirement. As Pusher's docs state:

> All events received and sent by clients can contain a data field. [...] In order to keep the protocol consistent, Pusher Channels tries to send the data field as a string.

it is not mandatory for events to have `data` property and there are only information about `data` property for presence channels. However, I believe it's worth considering providing it in private channels as the official Pusher API provides it and also their official Swift package ignores `subscription_succeeded` event if there is no data provided (https://github.com/pusher/pusher-websocket-swift/blob/master/Sources/Services/PusherConnection.swift#L448). The latter may be (of course) a bug, but for now they are complementary for one another.

It also looks like every pusher internal event contains `data` property, which is reasonable - they contain the actual data. This may be some kind of common algorithm and they do the same also for `subscription_succeeded` event - but this is just an allegation :)

**Comment by joedixon** [comment]
Thanks @jabools - would you be able to test this branch and see if it resolves all of your issues?

**Comment by szymjab** [comment]
@joedixon I'm responding from my work account :) I've just tested this branch and it works like a charm - iOS application works as expected, web application also works well and no side effects were noticed.
